# This is a basic workflow to help you get started with Actions
name: GitHub Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: string
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          ls
